#!/usr/bin/env bash
# quickstart.sh — bring up the Carbide2 Docker stack from a fresh checkout.
#
# What this does:
#   1. Verifies Docker + Compose are present.
#   2. Creates a .env file with reasonable dev defaults if one doesn't exist.
#   3. Builds and starts the stack (postgres + carbide).
#   4. Waits for the Rails health endpoint to return 200.
#   5. Prints the URLs and seeded dev credentials.
#
# Idempotent — safe to re-run. Pass --rebuild to force image rebuild,
# --shell to also build the (slow, ~4GB) carbide2-shell terminal image.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

REBUILD=0
BUILD_SHELL=0
for arg in "$@"; do
  case "$arg" in
    --rebuild) REBUILD=1 ;;
    --shell)   BUILD_SHELL=1 ;;
    -h|--help)
      sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) echo "[quickstart] unknown arg: $arg" >&2; exit 1 ;;
  esac
done

log() { printf '[quickstart] %s\n' "$*"; }
die() { printf '[quickstart] ERROR: %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# 1. Preflight
# ---------------------------------------------------------------------------
command -v docker >/dev/null 2>&1 || die "docker not found in PATH"
docker compose version >/dev/null 2>&1 || die "'docker compose' (v2) not available"

if ! docker info >/dev/null 2>&1; then
  die "cannot talk to Docker daemon — is it running, and is your user in the 'docker' group?
       (try: sudo usermod -aG docker \"\$USER\" && newgrp docker)"
fi

# ---------------------------------------------------------------------------
# 2. .env bootstrap
# ---------------------------------------------------------------------------
if [[ ! -f .env ]]; then
  log "no .env found — generating one with dev defaults"
  cat > .env <<'EOF'
# Generated by quickstart.sh. Edit freely.
RAILS_ENV=development
WORKER_JWT_SECRET=changeme-in-prod
WORKER_TOKEN_EXPIRY_SECONDS=600
# Leave OAuth blank to disable social login.
OAUTH_GITHUB_CLIENT_ID=
OAUTH_GITHUB_CLIENT_SECRET=
OAUTH_GOOGLE_CLIENT_ID=
OAUTH_GOOGLE_CLIENT_SECRET=
EOF
else
  log ".env exists — leaving it alone"
  if grep -qE '^DATABASE_URL=sqlite' .env; then
    die ".env contains a SQLite DATABASE_URL — this overrides Postgres and will break the stack.
       Comment that line out and re-run."
  fi
fi

# ---------------------------------------------------------------------------
# 3. Bring up the stack
# ---------------------------------------------------------------------------
BUILD_FLAG=""
[[ $REBUILD -eq 1 ]] && BUILD_FLAG="--build"

log "starting stack (docker compose up -d $BUILD_FLAG)"
docker compose up -d $BUILD_FLAG

if [[ $BUILD_SHELL -eq 1 ]]; then
  log "building carbide2-shell image (this is slow — ~4GB of toolchains)"
  docker build -f Dockerfile.shell -t carbide2-shell .
fi

# ---------------------------------------------------------------------------
# 4. Wait for Rails /up
# ---------------------------------------------------------------------------
log "waiting for Rails to come up at http://localhost:3000/up ..."
for i in $(seq 1 60); do
  if curl -fsS http://localhost:3000/up >/dev/null 2>&1; then
    log "Rails is up (took ~${i}s)"
    break
  fi
  if [[ $i -eq 60 ]]; then
    echo
    log "Rails didn't come up in 60s. Recent logs:"
    docker compose logs --tail=40 carbide
    die "stack did not become healthy"
  fi
  sleep 1
done

# ---------------------------------------------------------------------------
# 5. Done
# ---------------------------------------------------------------------------
cat <<EOF

  Carbide2 is up.

  Web UI:      http://localhost:5173
  Rails API:   http://localhost:3000
  Worker WS:   ws://localhost:8080
  Postgres:    localhost:5432 (user: carbide / pass: carbide / db: carbide2_development)

  Seeded dev login:
    email:     dev@example.com
    password:  password

  Useful commands:
    docker compose logs -f carbide       # tail server logs
    docker compose ps                    # service status
    docker compose down                  # stop stack (volumes preserved)
    docker compose down -v               # stop and WIPE all data
    ./scripts/import-host-dir.sh PATH ID # seed project ID workspace from a host dir

EOF
