require "active_support/core_ext/integer/time"
require "ipaddr"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # Host allowlist. Rails 8 blocks unknown Host: headers with a 403 by default.
  #
  # An allowlist is the wrong default for dev: the browser-facing FQDN (e.g.
  # dev1.frankd.local) is only known at deploy time, and a literal hostname in
  # the Host: header NEVER matches an RFC-1918 CIDR entry — so reaching the box
  # by name yielded a confusing 403 "Blocked hosts" even though the LAN IP was
  # allowlisted. For dev we therefore accept ANY host by default and let an
  # operator opt back into an allowlist via RAILS_DEV_HOSTS when they want to
  # tighten things (comma-separated; entries with '/' are IP CIDRs, entries
  # starting with '.' are domain suffixes). Empty or "*" => accept all hosts.
  config.hosts.clear
  dev_hosts = ENV.fetch("RAILS_DEV_HOSTS", "*").strip
  unless dev_hosts.empty? || dev_hosts == "*"
    dev_hosts.split(",").map(&:strip).reject(&:empty?).each do |h|
      config.hosts << (h.include?("/") ? IPAddr.new(h) : h)
    end
  end
  # When config.hosts is empty Rails accepts any Host:. Keep /up excluded so the
  # health endpoint answers even under a tightened allowlist (k8s probes, helm
  # tests, smoke checks).
  config.host_authorization = { exclude: ->(request) { request.path == "/up" } }
end
